os:
  - linux
  - osx

python:
  - 2.7
#sudo: required
sudo: false

before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then wget https://repo.continuum.io/miniconda/Miniconda2-latest-MacOSX-x86_64.sh; fi
  - export PATH="$HOME/miniconda/bin:$PATH"
  - export PREFIX="$HOME/miniconda"
  - export UDUNITS2_XML_PATH=$HOME/miniconda/share/udunits/udunits2.xml
  - export UVCDAT_ANONYMOUS_LOG=no
  - bash miniconda.sh -b -p $HOME/miniconda
  - conda config --set always_yes yes --set changeps1 no
  - conda update -y -q conda
  - conda install openssl=1.0.2d
  - conda install cdms2 -c uvcdat/label/nightly -c conda-forge -c uvcdat
  - conda install udunits2 -c uvcdat/label/nightly  -c conda-forge -c uvcdat
  - conda install gcc 
  - conda install nose

install:
    - git clone https://github.com/PCMDI/cmip6-cmor-tables 
    - ln -s cmip6-cmor-tables/Tables Tables
    - ./configure --prefix=$PREFIX --with-python --with-uuid=$PREFIX --with-udunits2=$PREFIX --with-netcdf=$PREFIX  
    - make install 

script: 
    - make test
    - for file in `ls -1 Test/test_python_CMIP6_CV*.py`; do echo $file; python $file; if [[ "$?" != "0" ]]; then return $?; fi; done
#    - nosetests -vv --collect-only Test/test_python_CMIP6_CV_*.py
#    - nosetests -vv --collect-only Test/test_python_has_*.py
#    - for file in `ls -1 Test/test_python_CMIP6_CV*.py`; do echo $file; python $file; done
#    - python run_tests2.py 
#    - python run_tests.py 

after_failure:
    - ulimit -a
    - free -m
    - find CMIP6/
    - df -kh ./
    - ls -lR
    - cat ~/build.sh
